apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hexagonal-bank
  annotations:
    github.com/project-slug: rahul-ratra/hexagonal-bank
spec:
  type: other
  lifecycle: unknown
  owner: guests
